# Generated by Django 5.0.3 on 2024-10-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_remove_product_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('owner_of_comment', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=10)),
                ('comment_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.product')),
            ],
        ),
    ]
