# Generated by Django 5.0.3 on 2024-06-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=8, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100, null=True)),
                ('cpass', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='customer_image/')),
            ],
        ),
    ]
