# Generated by Django 5.0.3 on 2024-08-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=8, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(upload_to='customer_image/')),
            ],
        ),
    ]
