# Generated by Django 5.0.3 on 2024-08-28 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.customer'),
        ),
    ]
