from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.Index.as_view()),
    # path('index/', views.Index_view.as_view(),name="index"),
    path('signup/', views.Signup_view.as_view(),name="signup"),
    path('login/', views.Login_view.as_view(),name="login"),
    path('logout/', views.Logout_view.as_view(),name="logout"),
    path('login_verify_otp/', views.Login_verify_otp_view.as_view(),name="login_verify_otp"),
    path('login/forget/', views.Forget_password_view.as_view(),name="forget_password_view"),
    path('login/send_mail/', views.Send_mail_view.as_view(),name="send_mail"),
    path('verify_otp/', views.NewUser_verify_otp_view.as_view(),name="verify_otp"),
    path('login/resend_mail/', views.Resend_mail_view.as_view(),name="resend_mail"),
    path('login/forget/reset_password/', views.Reset_password_view.as_view(),name="reset_password_view"),
    path('filter/', views.Filter_category_index_view.as_view(),name="filter"),
    path('price/', views.PriceFilterIndex_view.as_view(),name="price"),
    path('add_to_cart/', views.Add_to_cart_view.as_view(),name="addtocart"),
    # path('add_to_cart/', views.CAdd_to_cart_view.as_view(),name="add_to_cart"),
    # path('add/', views.Add_cart_view.as_view(),name="add"),
    path('profile/add_to_cart/', views.CustomerAdd_to_cart_view.as_view(),name="customeraddtocart"),
    path('profile/update_cart/', views.Customer_update_cart_view.as_view(),name="updatecart"),
    path('profile/update_indexcart/', views.update_cart_view.as_view(),name="updateindexcart"),
    path('viewcart/', views.Viewcart_Index_view.as_view()),
    path('viewcart/less_items/', views.Less_item_incart.as_view()),
    path('viewcart/add_items/', views.Add_item_incart.as_view()),
    path('viewcart/del_items/', views.Delete_item_incart.as_view(),name='delete'),
    path('profile/', views.Customer_profile_view.as_view()),
    path('profile/filter/', views.Filter_category_view.as_view(),name="userfilter"),
    path('profile/price/', views.PriceFilter_view.as_view(),name="userprice"),
    path('profile/details/', views.Customerprofile_view.as_view(),name="details"),
    path('profile/viewcart/', views.Viewcart_view.as_view(),name="userviewcart"),
    # path('profile/logout/', views.Customerlogout_view.as_view()),
    path('profile/viewcart/less_items/', views.Customer_less_item_incart_view.as_view()),
    path('profile/viewcart/add_items/', views.Customer_add_item_incart.as_view()),
    path('profile/viewcart/del_items/', views.Customer_delete_item_incart.as_view()),
    path('profile/viewcart/checkout/', views.Checkout_view.as_view()),
    path('profile/viewcart/address/', views.Address_view.as_view()),
    path('profile/viewcart/address/editaddress/', views.EditAddress_view.as_view()),
    path('profile/viewcart/address/newaddress/', views.NewAddress_create_view.as_view()),
    path('profile/viewcart/address/updateaddress/', views.UpdateAddress_view.as_view()),
    # path('add_product/', views.Index_addproduct_view.as_view()),
    # path('custadd_product/', views.Customer_addproduct_view.as_view(),name="addpro"),
    # path('cart/', views.Addproduct_incart_view.as_view(),name="cart"),
    # path('cartindex/', views.Addproduct_Incart_Index_view.as_view(),name="cartindex"),
    # path('add/', views.Addproduct_view.as_view(),name="add"),
    # path('session/', views.customerindex_setsession_view,name="session"),
    path('profile/profile_details/change_profile/', views.ChangeProfile_view.as_view()),
    path('profile/profile_details/change_img/', views.ChangeImg_view.as_view()),
    path('profile/profile_details/delete_img/', views.DeleteImg_view.as_view()),
    path('profile/profile_details/change_password/', views.Changepwd_view.as_view()),
    path('profile/viewcart/checkout/invoice/', views.Invoice_view.as_view()),
    path('profile/viewcart/checkout/invoice/download/', views.DownloadInvoice_view.as_view()),
    # path('customer_profile/delcart/', views.Delcart_view.as_view(),name="customer_profile/delcart"),
    # path('customerview/<cid>', views.customer_category_filter_view,name="customerindex"),
    # path('confirm_action/', views.confirm_action, name='confirm_action'),
    path('add/' ,views.add),
    path('update_indexcart/' ,views.update_add),
    path('customeradd/' ,views.customeradd),
    path('update_viewcart/' ,views.update_customeradd),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)